//Components
export const SET_BUYER_SOURCE = "SET_BUYER_SOURCE";
export const SET_SELLER_ASK = "SET_SELLER_ASK";
export const SET_WALLET_ID = "SET_WALLET_ID";
export const SET_DEV_MODE = "SET_DEV_MODE";
//Errors
export const SET_ALERT_ERROR = "SET_ALERT_ERROR";
export const SET_ALERT_WARNING = "SET_ALERT_WARNING";
export const SET_ALERT_INFO = "SET_ALERT_INFO";
export const SET_ALERT_SUCCESS = "SET_ALERT_SUCCESS";
//Auth
export const INITIAL = 'INITIAL'
export const FETCHING_ACCOUNTS = 'FETCHING_ACCOUNTS'
export const ACCOUNTS_FETCHED = 'ACCOUNTS_FETCHED'
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR'
export const ACCOUNTS_CHANGED = 'ACCOUNTS_CHANGED'
//EVM
export const evmErrorStatuses = {
    NO_ETHEREUM_FOUND: 'NO_ETHEREUM_FOUND',
    NO_ACCOUNTS_FOUND: 'NO_ACCOUNTS_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
  }
export const ETH_NOT_SUPPORTED = 'ETH_NOT_SUPPORTED'
export const ETH_EMPTY_WALLET = 'ETH_EMPTY_WALLET'
export const ETH_CONNECTION_ERROR = 'ETH_CONNECTION_ERROR'
export const ETH_CONNECTED = 'ETH_CONNECTED'
export const ETH_DISCONNECTED = 'ETH_DISCONNECTED'
export const ETH_CONNECTING_WALLET = 'ETH_CONNECTING_WALLET'
//LOCAL
export const FETCHING_LOCAL = 'FETCHING_LOCAL'